name: cli-ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cli
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
          cache: true
          cache-dependency-path: go.sum
      - name: Test
        run: go test ./...
      - name: Test without workspace
        run: GOWORK=off go test ./...
      - name: Build
        run: CGO_ENABLED=0 go build -o /tmp/soha ./cmd/soha
